# Read results

In [1]:
import os
import pickle

import pandas as pd
import numpy as np

## Leukemia

In [4]:
p_values = [2000, 4000, 6000, 8000, 10000]
n__values =  [50, 40, 30] # not the real n's (which are computed in the notebook)s!
percent_values = [1.25, 2.5, 5.0, 10.0]

In [2]:
cwd = os.getcwd()
cwd

'/Users/jeremie.cabessau-paris2.fr/Desktop/MAIN/Students/2024_Nourane_Fradi/code'

In [3]:
p = 2000

results_folder = os.path.join(cwd, f"results/synthetic_data_{p}")
results_folder

'/Users/jeremie.cabessau-paris2.fr/Desktop/MAIN/Students/2024_Nourane_Fradi/code/results/synthetic_data_2000'

In [53]:
results_d = {}

for p in p_values:

    results_folder = os.path.join(cwd, f"results/synthetic_data_{p}")
    results_folder

    ns = [int(p//n_) for n_ in n__values]
    nzs = [int(p*percent//100) for percent in percent_values]

    fts_modes = ["full", "random", "k-best", "k-best-mi", "pk-lpnn"]
    models = ["knn", "lr", "nb-gaussian", "svc"]
        
    results_d[p] = {}

    for n in ns:

        results_d[p][n] = {}

        for nz in nzs:

            results_d[p][n][nz] = {}

            for fts_mode in fts_modes:

                results_d[p][n][nz][fts_mode] = {}

                for model in models:

                    with open( os.path.join(results_folder, f"{n}", f"{nz}", f"{fts_mode}_{nz}_{model}.pkl"), "rb" ) as fh:

                        results = pickle.load(fh)
                        f1 = np.mean(results["f1"]).round(3)
                        b_acc = np.mean(results["b_acc"]).round(3)
                        #Â print("f1: ", f1, "b_acc: ", b_acc)

                        results_d[p][n][nz][fts_mode][model] = (f1, b_acc)

In [57]:
results_df = {}

for p in p_values:
    
    print("****************")
    print(f"*** p = {p} ***")
    print("****************\n")
    
    ns = [int(p//n_) for n_ in n__values]
    nzs = [int(p*percent//100) for percent in percent_values]
    
    results_df[p] = {}
    
    for n in ns:

        results_df[p][n] = {}

        for nz in nzs:

            results_df[p][n][nz] = pd.DataFrame.from_dict(results_d[p][n][nz])
            
            print(f"*** n = {n}, N_z = {nz} ***")
            display(results_df[p][n][nz])
            print("\n")

****************
*** p = 2000 ***
****************

*** n = 40, N_z = 25 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.634, 0.698)","(0.461, 0.529)","(0.543, 0.624)","(0.471, 0.549)","(0.495, 0.556)"
lr,"(0.607, 0.674)","(0.441, 0.499)","(0.522, 0.588)","(0.559, 0.628)","(0.503, 0.558)"
nb-gaussian,"(0.356, 0.443)","(0.437, 0.498)","(0.548, 0.607)","(0.429, 0.516)","(0.529, 0.594)"
svc,"(0.392, 0.559)","(0.422, 0.511)","(0.506, 0.568)","(0.517, 0.585)","(0.502, 0.564)"

*** n = 40, N_z = 50 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.792, 0.832)","(0.402, 0.473)","(0.59, 0.659)","(0.443, 0.511)","(0.574, 0.633)"
lr,"(0.735, 0.78)","(0.415, 0.491)","(0.609, 0.678)","(0.497, 0.556)","(0.58, 0.638)"
nb-gaussian,"(0.473, 0.547)","(0.444, 0.509)","(0.351, 0.424)","(0.493, 0.559)","(0.419, 0.476)"
svc,"(0.628, 0.698)","(0.371, 0.474)","(0.606, 0.668)","(0.47, 0.535)","(0.58, 0.633)"

*** n = 40, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.764, 0.811)","(0.424, 0.491)","(0.841, 0.883)","(0.637, 0.701)","(0.652, 0.712)"
lr,"(0.713, 0.776)","(0.503, 0.563)","(0.846, 0.874)","(0.64, 0.693)","(0.638, 0.7)"
nb-gaussian,"(0.464, 0.56)","(0.446, 0.511)","(0.532, 0.608)","(0.442, 0.522)","(0.485, 0.547)"
svc,"(0.683, 0.759)","(0.447, 0.524)","(0.888, 0.912)","(0.663, 0.738)","(0.651, 0.708)"

*** n = 40, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.711, 0.768)","(0.479, 0.55)","(0.608, 0.685)","(0.613, 0.689)","(0.573, 0.644)"
lr,"(0.792, 0.842)","(0.531, 0.594)","(0.641, 0.713)","(0.665, 0.726)","(0.551, 0.632)"
nb-gaussian,"(0.429, 0.542)","(0.391, 0.471)","(0.531, 0.618)","(0.411, 0.501)","(0.469, 0.538)"
svc,"(0.623, 0.711)","(0.513, 0.59)","(0.645, 0.716)","(0.725, 0.79)","(0.574, 0.652)"

*** n = 50, N_z = 25 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.811, 0.853)","(0.391, 0.446)","(0.885, 0.914)","(0.701, 0.749)","(0.903, 0.929)"
lr,"(0.822, 0.861)","(0.442, 0.501)","(0.867, 0.898)","(0.594, 0.646)","(0.852, 0.881)"
nb-gaussian,"(0.445, 0.549)","(0.441, 0.493)","(0.806, 0.849)","(0.559, 0.621)","(0.83, 0.865)"
svc,"(0.557, 0.697)","(0.402, 0.493)","(0.874, 0.903)","(0.67, 0.725)","(0.884, 0.91)"

*** n = 50, N_z = 50 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.856, 0.898)","(0.395, 0.468)","(0.728, 0.784)","(0.57, 0.638)","(0.677, 0.747)"
lr,"(0.886, 0.914)","(0.44, 0.521)","(0.699, 0.766)","(0.503, 0.569)","(0.655, 0.718)"
nb-gaussian,"(0.472, 0.573)","(0.428, 0.514)","(0.61, 0.683)","(0.384, 0.453)","(0.541, 0.611)"
svc,"(0.71, 0.786)","(0.382, 0.49)","(0.725, 0.785)","(0.577, 0.652)","(0.696, 0.76)"

*** n = 50, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.609, 0.687)","(0.48, 0.544)","(0.357, 0.407)","(0.462, 0.531)","(0.441, 0.497)"
lr,"(0.665, 0.708)","(0.517, 0.57)","(0.427, 0.495)","(0.502, 0.561)","(0.479, 0.528)"
nb-gaussian,"(0.516, 0.6)","(0.472, 0.527)","(0.564, 0.628)","(0.469, 0.542)","(0.516, 0.56)"
svc,"(0.505, 0.625)","(0.479, 0.564)","(0.394, 0.453)","(0.525, 0.582)","(0.463, 0.526)"

*** n = 50, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.71, 0.758)","(0.506, 0.56)","(0.53, 0.594)","(0.52, 0.591)","(0.513, 0.575)"
lr,"(0.593, 0.635)","(0.491, 0.545)","(0.468, 0.531)","(0.433, 0.502)","(0.48, 0.542)"
nb-gaussian,"(0.447, 0.52)","(0.461, 0.52)","(0.505, 0.58)","(0.297, 0.358)","(0.46, 0.538)"
svc,"(0.558, 0.656)","(0.496, 0.56)","(0.583, 0.642)","(0.555, 0.62)","(0.501, 0.551)"

*** n = 66, N_z = 25 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.756, 0.789)","(0.415, 0.47)","(0.759, 0.794)","(0.531, 0.587)","(0.799, 0.826)"
lr,"(0.848, 0.881)","(0.446, 0.494)","(0.762, 0.799)","(0.511, 0.56)","(0.772, 0.803)"
nb-gaussian,"(0.515, 0.573)","(0.45, 0.503)","(0.667, 0.714)","(0.434, 0.483)","(0.624, 0.669)"
svc,"(0.576, 0.685)","(0.418, 0.489)","(0.789, 0.824)","(0.565, 0.614)","(0.804, 0.831)"

*** n = 66, N_z = 50 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.844, 0.87)","(0.457, 0.501)","(0.633, 0.679)","(0.634, 0.681)","(0.659, 0.704)"
lr,"(0.875, 0.893)","(0.481, 0.518)","(0.634, 0.669)","(0.601, 0.65)","(0.638, 0.681)"
nb-gaussian,"(0.619, 0.682)","(0.481, 0.523)","(0.572, 0.625)","(0.511, 0.558)","(0.545, 0.587)"
svc,"(0.803, 0.853)","(0.458, 0.526)","(0.658, 0.699)","(0.657, 0.7)","(0.681, 0.725)"

*** n = 66, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.837, 0.87)","(0.5, 0.556)","(0.661, 0.71)","(0.494, 0.552)","(0.588, 0.646)"
lr,"(0.788, 0.823)","(0.55, 0.611)","(0.65, 0.701)","(0.502, 0.549)","(0.591, 0.655)"
nb-gaussian,"(0.591, 0.669)","(0.552, 0.61)","(0.612, 0.67)","(0.552, 0.609)","(0.591, 0.641)"
svc,"(0.735, 0.804)","(0.528, 0.602)","(0.66, 0.711)","(0.495, 0.55)","(0.595, 0.658)"

*** n = 66, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.771, 0.814)","(0.483, 0.543)","(0.596, 0.643)","(0.567, 0.611)","(0.548, 0.605)"
lr,"(0.639, 0.689)","(0.455, 0.499)","(0.527, 0.571)","(0.515, 0.559)","(0.555, 0.609)"
nb-gaussian,"(0.404, 0.467)","(0.425, 0.488)","(0.396, 0.45)","(0.476, 0.525)","(0.442, 0.495)"
svc,"(0.629, 0.694)","(0.472, 0.527)","(0.573, 0.622)","(0.573, 0.614)","(0.554, 0.609)"

****************
*** p = 4000 ***
****************

*** n = 80, N_z = 50 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.869, 0.895)","(0.48, 0.523)","(0.76, 0.79)","(0.617, 0.652)","(0.737, 0.77)"
lr,"(0.909, 0.925)","(0.459, 0.504)","(0.732, 0.766)","(0.557, 0.602)","(0.736, 0.766)"
nb-gaussian,"(0.582, 0.661)","(0.46, 0.506)","(0.657, 0.698)","(0.545, 0.59)","(0.665, 0.701)"
svc,"(0.851, 0.898)","(0.471, 0.546)","(0.785, 0.813)","(0.628, 0.67)","(0.757, 0.781)"

*** n = 80, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.845, 0.865)","(0.482, 0.533)","(0.521, 0.566)","(0.467, 0.506)","(0.54, 0.582)"
lr,"(0.714, 0.743)","(0.489, 0.534)","(0.5, 0.528)","(0.43, 0.465)","(0.514, 0.555)"
nb-gaussian,"(0.375, 0.45)","(0.465, 0.527)","(0.438, 0.472)","(0.489, 0.517)","(0.46, 0.492)"
svc,"(0.664, 0.724)","(0.481, 0.546)","(0.508, 0.557)","(0.436, 0.49)","(0.565, 0.607)"

*** n = 80, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.88, 0.897)","(0.528, 0.575)","(0.721, 0.753)","(0.587, 0.618)","(0.611, 0.64)"
lr,"(0.78, 0.808)","(0.528, 0.569)","(0.758, 0.783)","(0.588, 0.621)","(0.65, 0.681)"
nb-gaussian,"(0.525, 0.593)","(0.463, 0.498)","(0.639, 0.68)","(0.532, 0.569)","(0.578, 0.618)"
svc,"(0.778, 0.812)","(0.551, 0.596)","(0.753, 0.783)","(0.565, 0.605)","(0.647, 0.674)"

*** n = 80, N_z = 400 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.76, 0.794)","(0.514, 0.564)","(0.639, 0.679)","(0.523, 0.558)","(0.587, 0.639)"
lr,"(0.631, 0.665)","(0.525, 0.572)","(0.596, 0.634)","(0.507, 0.532)","(0.568, 0.6)"
nb-gaussian,"(0.408, 0.482)","(0.481, 0.53)","(0.384, 0.437)","(0.475, 0.528)","(0.454, 0.497)"
svc,"(0.647, 0.708)","(0.539, 0.598)","(0.614, 0.656)","(0.528, 0.567)","(0.573, 0.618)"

*** n = 100, N_z = 50 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.89, 0.9)","(0.513, 0.541)","(0.738, 0.763)","(0.458, 0.493)","(0.774, 0.794)"
lr,"(0.824, 0.843)","(0.498, 0.526)","(0.682, 0.708)","(0.492, 0.515)","(0.714, 0.736)"
nb-gaussian,"(0.537, 0.585)","(0.486, 0.513)","(0.633, 0.661)","(0.442, 0.471)","(0.637, 0.659)"
svc,"(0.813, 0.847)","(0.502, 0.538)","(0.746, 0.769)","(0.485, 0.518)","(0.768, 0.785)"

*** n = 100, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.851, 0.861)","(0.498, 0.527)","(0.763, 0.779)","(0.514, 0.536)","(0.712, 0.738)"
lr,"(0.808, 0.824)","(0.478, 0.503)","(0.744, 0.763)","(0.478, 0.509)","(0.678, 0.7)"
nb-gaussian,"(0.384, 0.438)","(0.461, 0.489)","(0.561, 0.597)","(0.437, 0.473)","(0.545, 0.578)"
svc,"(0.817, 0.845)","(0.483, 0.526)","(0.79, 0.81)","(0.569, 0.592)","(0.745, 0.771)"

*** n = 100, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.861, 0.874)","(0.541, 0.572)","(0.676, 0.705)","(0.592, 0.625)","(0.605, 0.638)"
lr,"(0.714, 0.737)","(0.531, 0.557)","(0.659, 0.686)","(0.592, 0.624)","(0.612, 0.641)"
nb-gaussian,"(0.493, 0.549)","(0.487, 0.521)","(0.558, 0.593)","(0.523, 0.564)","(0.548, 0.579)"
svc,"(0.763, 0.798)","(0.544, 0.583)","(0.681, 0.71)","(0.643, 0.675)","(0.633, 0.66)"

*** n = 100, N_z = 400 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.854, 0.877)","(0.55, 0.579)","(0.689, 0.726)","(0.594, 0.628)","(0.61, 0.648)"
lr,"(0.722, 0.745)","(0.544, 0.575)","(0.655, 0.682)","(0.584, 0.614)","(0.583, 0.616)"
nb-gaussian,"(0.471, 0.538)","(0.456, 0.494)","(0.497, 0.545)","(0.547, 0.591)","(0.506, 0.554)"
svc,"(0.695, 0.759)","(0.535, 0.572)","(0.7, 0.732)","(0.592, 0.628)","(0.617, 0.655)"

*** n = 133, N_z = 50 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.919, 0.925)","(0.491, 0.513)","(0.767, 0.784)","(0.583, 0.601)","(0.763, 0.776)"
lr,"(0.819, 0.829)","(0.496, 0.515)","(0.741, 0.756)","(0.542, 0.567)","(0.722, 0.732)"
nb-gaussian,"(0.517, 0.554)","(0.495, 0.512)","(0.593, 0.614)","(0.51, 0.535)","(0.578, 0.591)"
svc,"(0.809, 0.833)","(0.488, 0.52)","(0.793, 0.807)","(0.605, 0.625)","(0.787, 0.798)"

*** n = 133, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.898, 0.906)","(0.501, 0.525)","(0.715, 0.727)","(0.54, 0.564)","(0.704, 0.72)"
lr,"(0.865, 0.871)","(0.498, 0.519)","(0.725, 0.737)","(0.527, 0.551)","(0.666, 0.682)"
nb-gaussian,"(0.546, 0.577)","(0.478, 0.502)","(0.589, 0.611)","(0.545, 0.566)","(0.563, 0.578)"
svc,"(0.864, 0.878)","(0.501, 0.539)","(0.763, 0.774)","(0.586, 0.605)","(0.725, 0.74)"

*** n = 133, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.93, 0.938)","(0.525, 0.549)","(0.695, 0.713)","(0.543, 0.565)","(0.664, 0.681)"
lr,"(0.782, 0.796)","(0.532, 0.552)","(0.738, 0.754)","(0.533, 0.55)","(0.657, 0.671)"
nb-gaussian,"(0.59, 0.618)","(0.504, 0.525)","(0.619, 0.637)","(0.467, 0.487)","(0.559, 0.579)"
svc,"(0.819, 0.837)","(0.564, 0.593)","(0.744, 0.761)","(0.576, 0.593)","(0.693, 0.711)"

*** n = 133, N_z = 400 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.898, 0.908)","(0.559, 0.58)","(0.746, 0.759)","(0.596, 0.615)","(0.651, 0.67)"
lr,"(0.753, 0.765)","(0.541, 0.554)","(0.647, 0.66)","(0.564, 0.582)","(0.632, 0.651)"
nb-gaussian,"(0.618, 0.646)","(0.533, 0.55)","(0.62, 0.643)","(0.531, 0.553)","(0.56, 0.581)"
svc,"(0.77, 0.792)","(0.58, 0.601)","(0.719, 0.734)","(0.596, 0.617)","(0.678, 0.699)"

****************
*** p = 6000 ***
****************

*** n = 120, N_z = 75 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.842, 0.856)","(0.507, 0.535)","(0.763, 0.777)","(0.521, 0.541)","(0.717, 0.733)"
lr,"(0.826, 0.839)","(0.497, 0.516)","(0.647, 0.673)","(0.495, 0.512)","(0.605, 0.627)"
nb-gaussian,"(0.599, 0.634)","(0.486, 0.508)","(0.568, 0.59)","(0.545, 0.568)","(0.538, 0.559)"
svc,"(0.784, 0.82)","(0.509, 0.54)","(0.773, 0.79)","(0.548, 0.573)","(0.705, 0.723)"

*** n = 120, N_z = 150 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.898, 0.911)","(0.513, 0.544)","(0.555, 0.587)","(0.505, 0.535)","(0.549, 0.575)"
lr,"(0.787, 0.805)","(0.501, 0.531)","(0.593, 0.619)","(0.451, 0.475)","(0.616, 0.64)"
nb-gaussian,"(0.514, 0.558)","(0.481, 0.505)","(0.562, 0.591)","(0.454, 0.479)","(0.58, 0.608)"
svc,"(0.746, 0.787)","(0.483, 0.527)","(0.597, 0.624)","(0.492, 0.52)","(0.61, 0.64)"

*** n = 120, N_z = 300 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.842, 0.86)","(0.532, 0.559)","(0.644, 0.673)","(0.562, 0.592)","(0.609, 0.644)"
lr,"(0.831, 0.846)","(0.537, 0.563)","(0.698, 0.722)","(0.524, 0.551)","(0.653, 0.672)"
nb-gaussian,"(0.515, 0.575)","(0.491, 0.518)","(0.54, 0.571)","(0.425, 0.453)","(0.526, 0.554)"
svc,"(0.779, 0.815)","(0.553, 0.587)","(0.7, 0.727)","(0.579, 0.613)","(0.66, 0.686)"

*** n = 120, N_z = 600 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.83, 0.841)","(0.546, 0.569)","(0.635, 0.655)","(0.535, 0.562)","(0.598, 0.619)"
lr,"(0.676, 0.688)","(0.528, 0.556)","(0.605, 0.618)","(0.511, 0.531)","(0.568, 0.582)"
nb-gaussian,"(0.527, 0.563)","(0.51, 0.538)","(0.506, 0.539)","(0.507, 0.535)","(0.522, 0.543)"
svc,"(0.692, 0.726)","(0.572, 0.604)","(0.637, 0.655)","(0.527, 0.549)","(0.607, 0.629)"

*** n = 150, N_z = 75 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.951, 0.954)","(0.493, 0.516)","(0.725, 0.74)","(0.568, 0.585)","(0.724, 0.74)"
lr,"(0.846, 0.854)","(0.489, 0.505)","(0.686, 0.702)","(0.569, 0.588)","(0.698, 0.711)"
nb-gaussian,"(0.606, 0.639)","(0.492, 0.507)","(0.663, 0.679)","(0.513, 0.53)","(0.652, 0.666)"
svc,"(0.823, 0.844)","(0.488, 0.518)","(0.764, 0.776)","(0.585, 0.607)","(0.758, 0.771)"

*** n = 150, N_z = 150 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.934, 0.939)","(0.512, 0.533)","(0.662, 0.678)","(0.497, 0.524)","(0.62, 0.639)"
lr,"(0.789, 0.799)","(0.502, 0.523)","(0.585, 0.603)","(0.493, 0.513)","(0.614, 0.632)"
nb-gaussian,"(0.558, 0.589)","(0.487, 0.509)","(0.512, 0.534)","(0.538, 0.559)","(0.564, 0.579)"
svc,"(0.812, 0.827)","(0.545, 0.574)","(0.675, 0.69)","(0.532, 0.562)","(0.651, 0.67)"

*** n = 150, N_z = 300 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.802, 0.821)","(0.528, 0.551)","(0.633, 0.654)","(0.527, 0.546)","(0.586, 0.606)"
lr,"(0.742, 0.755)","(0.531, 0.545)","(0.556, 0.577)","(0.507, 0.522)","(0.571, 0.589)"
nb-gaussian,"(0.591, 0.618)","(0.52, 0.539)","(0.544, 0.566)","(0.542, 0.565)","(0.544, 0.563)"
svc,"(0.78, 0.807)","(0.571, 0.594)","(0.647, 0.664)","(0.503, 0.525)","(0.615, 0.637)"

*** n = 150, N_z = 600 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.881, 0.891)","(0.541, 0.565)","(0.649, 0.671)","(0.563, 0.587)","(0.604, 0.63)"
lr,"(0.727, 0.744)","(0.551, 0.57)","(0.72, 0.737)","(0.549, 0.574)","(0.61, 0.631)"
nb-gaussian,"(0.532, 0.567)","(0.517, 0.537)","(0.56, 0.585)","(0.512, 0.534)","(0.53, 0.559)"
svc,"(0.704, 0.744)","(0.567, 0.594)","(0.706, 0.726)","(0.572, 0.601)","(0.625, 0.647)"

*** n = 200, N_z = 75 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.904, 0.911)","(0.489, 0.507)","(0.752, 0.765)","(0.527, 0.544)","(0.75, 0.763)"
lr,"(0.842, 0.852)","(0.486, 0.504)","(0.722, 0.735)","(0.536, 0.553)","(0.745, 0.756)"
nb-gaussian,"(0.583, 0.608)","(0.494, 0.507)","(0.704, 0.716)","(0.554, 0.57)","(0.667, 0.678)"
svc,"(0.817, 0.831)","(0.502, 0.526)","(0.796, 0.807)","(0.552, 0.567)","(0.783, 0.793)"

*** n = 200, N_z = 150 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.913, 0.917)","(0.514, 0.532)","(0.778, 0.79)","(0.54, 0.557)","(0.699, 0.714)"
lr,"(0.84, 0.848)","(0.502, 0.516)","(0.678, 0.694)","(0.518, 0.53)","(0.648, 0.661)"
nb-gaussian,"(0.581, 0.606)","(0.52, 0.533)","(0.572, 0.593)","(0.489, 0.503)","(0.538, 0.554)"
svc,"(0.86, 0.869)","(0.524, 0.546)","(0.783, 0.795)","(0.561, 0.582)","(0.742, 0.755)"

*** n = 200, N_z = 300 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.915, 0.921)","(0.537, 0.55)","(0.729, 0.741)","(0.553, 0.573)","(0.657, 0.67)"
lr,"(0.808, 0.817)","(0.519, 0.531)","(0.678, 0.689)","(0.608, 0.624)","(0.652, 0.664)"
nb-gaussian,"(0.538, 0.565)","(0.502, 0.52)","(0.58, 0.598)","(0.52, 0.539)","(0.541, 0.553)"
svc,"(0.856, 0.866)","(0.565, 0.582)","(0.749, 0.76)","(0.621, 0.637)","(0.707, 0.719)"

*** n = 200, N_z = 600 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.846, 0.853)","(0.561, 0.581)","(0.67, 0.684)","(0.568, 0.589)","(0.625, 0.638)"
lr,"(0.765, 0.775)","(0.574, 0.586)","(0.708, 0.716)","(0.611, 0.628)","(0.622, 0.633)"
nb-gaussian,"(0.583, 0.608)","(0.518, 0.534)","(0.616, 0.631)","(0.526, 0.541)","(0.559, 0.576)"
svc,"(0.812, 0.828)","(0.612, 0.627)","(0.729, 0.74)","(0.632, 0.65)","(0.664, 0.677)"

****************
*** p = 8000 ***
****************

*** n = 160, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.897, 0.904)","(0.48, 0.511)","(0.744, 0.761)","(0.549, 0.568)","(0.728, 0.743)"
lr,"(0.871, 0.878)","(0.486, 0.504)","(0.764, 0.78)","(0.538, 0.561)","(0.743, 0.755)"
nb-gaussian,"(0.59, 0.622)","(0.492, 0.511)","(0.64, 0.655)","(0.553, 0.577)","(0.642, 0.657)"
svc,"(0.856, 0.872)","(0.517, 0.543)","(0.812, 0.825)","(0.566, 0.593)","(0.783, 0.796)"

*** n = 160, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.876, 0.887)","(0.493, 0.516)","(0.654, 0.674)","(0.484, 0.504)","(0.63, 0.651)"
lr,"(0.79, 0.803)","(0.483, 0.503)","(0.69, 0.709)","(0.509, 0.526)","(0.601, 0.616)"
nb-gaussian,"(0.414, 0.456)","(0.475, 0.499)","(0.541, 0.569)","(0.472, 0.496)","(0.498, 0.522)"
svc,"(0.803, 0.825)","(0.512, 0.538)","(0.707, 0.725)","(0.482, 0.506)","(0.683, 0.703)"

*** n = 160, N_z = 400 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.874, 0.881)","(0.525, 0.544)","(0.66, 0.677)","(0.529, 0.549)","(0.605, 0.625)"
lr,"(0.687, 0.701)","(0.515, 0.531)","(0.619, 0.639)","(0.506, 0.523)","(0.577, 0.593)"
nb-gaussian,"(0.467, 0.501)","(0.466, 0.489)","(0.483, 0.506)","(0.489, 0.505)","(0.493, 0.514)"
svc,"(0.726, 0.749)","(0.549, 0.569)","(0.639, 0.659)","(0.527, 0.545)","(0.621, 0.642)"

*** n = 160, N_z = 800 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.877, 0.89)","(0.583, 0.605)","(0.628, 0.645)","(0.55, 0.579)","(0.605, 0.625)"
lr,"(0.659, 0.674)","(0.549, 0.567)","(0.566, 0.584)","(0.581, 0.598)","(0.587, 0.606)"
nb-gaussian,"(0.529, 0.568)","(0.499, 0.52)","(0.548, 0.571)","(0.522, 0.545)","(0.511, 0.529)"
svc,"(0.687, 0.727)","(0.587, 0.609)","(0.649, 0.668)","(0.585, 0.614)","(0.606, 0.625)"

*** n = 200, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.891, 0.898)","(0.501, 0.519)","(0.621, 0.632)","(0.495, 0.51)","(0.609, 0.621)"
lr,"(0.806, 0.814)","(0.485, 0.499)","(0.549, 0.565)","(0.511, 0.528)","(0.533, 0.546)"
nb-gaussian,"(0.582, 0.606)","(0.499, 0.513)","(0.506, 0.521)","(0.522, 0.538)","(0.511, 0.524)"
svc,"(0.793, 0.811)","(0.527, 0.555)","(0.656, 0.669)","(0.524, 0.54)","(0.645, 0.658)"

*** n = 200, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.943, 0.946)","(0.511, 0.525)","(0.714, 0.726)","(0.571, 0.588)","(0.677, 0.689)"
lr,"(0.837, 0.842)","(0.509, 0.52)","(0.707, 0.717)","(0.54, 0.555)","(0.642, 0.652)"
nb-gaussian,"(0.518, 0.544)","(0.478, 0.492)","(0.612, 0.626)","(0.522, 0.536)","(0.571, 0.582)"
svc,"(0.866, 0.874)","(0.541, 0.558)","(0.757, 0.768)","(0.603, 0.615)","(0.692, 0.703)"

*** n = 200, N_z = 400 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.829, 0.841)","(0.535, 0.554)","(0.619, 0.634)","(0.566, 0.585)","(0.59, 0.605)"
lr,"(0.737, 0.746)","(0.523, 0.535)","(0.613, 0.625)","(0.533, 0.548)","(0.587, 0.599)"
nb-gaussian,"(0.498, 0.529)","(0.502, 0.517)","(0.458, 0.477)","(0.472, 0.493)","(0.473, 0.491)"
svc,"(0.774, 0.789)","(0.571, 0.591)","(0.642, 0.655)","(0.591, 0.607)","(0.636, 0.649)"

*** n = 200, N_z = 800 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.855, 0.863)","(0.571, 0.585)","(0.632, 0.646)","(0.566, 0.588)","(0.605, 0.622)"
lr,"(0.636, 0.647)","(0.528, 0.54)","(0.595, 0.606)","(0.515, 0.523)","(0.556, 0.57)"
nb-gaussian,"(0.57, 0.59)","(0.522, 0.537)","(0.56, 0.572)","(0.551, 0.564)","(0.529, 0.543)"
svc,"(0.687, 0.71)","(0.568, 0.584)","(0.612, 0.623)","(0.57, 0.587)","(0.587, 0.598)"

*** n = 266, N_z = 100 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.951, 0.955)","(0.502, 0.518)","(0.824, 0.832)","(0.586, 0.599)","(0.808, 0.816)"
lr,"(0.854, 0.859)","(0.492, 0.502)","(0.763, 0.772)","(0.498, 0.509)","(0.773, 0.782)"
nb-gaussian,"(0.582, 0.6)","(0.484, 0.495)","(0.688, 0.7)","(0.527, 0.54)","(0.669, 0.68)"
svc,"(0.881, 0.89)","(0.486, 0.508)","(0.881, 0.887)","(0.605, 0.617)","(0.863, 0.869)"

*** n = 266, N_z = 200 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.929, 0.932)","(0.529, 0.539)","(0.741, 0.749)","(0.547, 0.558)","(0.699, 0.708)"
lr,"(0.826, 0.831)","(0.487, 0.498)","(0.71, 0.718)","(0.479, 0.489)","(0.669, 0.677)"
nb-gaussian,"(0.538, 0.553)","(0.481, 0.49)","(0.581, 0.589)","(0.486, 0.495)","(0.554, 0.56)"
svc,"(0.856, 0.863)","(0.529, 0.545)","(0.759, 0.766)","(0.579, 0.589)","(0.727, 0.735)"

*** n = 266, N_z = 400 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.916, 0.92)","(0.524, 0.536)","(0.722, 0.73)","(0.543, 0.554)","(0.662, 0.672)"
lr,"(0.81, 0.816)","(0.524, 0.537)","(0.682, 0.692)","(0.541, 0.552)","(0.645, 0.655)"
nb-gaussian,"(0.566, 0.584)","(0.506, 0.518)","(0.611, 0.624)","(0.49, 0.503)","(0.567, 0.579)"
svc,"(0.839, 0.848)","(0.568, 0.581)","(0.72, 0.73)","(0.586, 0.601)","(0.699, 0.709)"

*** n = 266, N_z = 800 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.901, 0.907)","(0.565, 0.582)","(0.682, 0.693)","(0.591, 0.604)","(0.627, 0.64)"
lr,"(0.713, 0.718)","(0.545, 0.553)","(0.623, 0.63)","(0.584, 0.592)","(0.598, 0.608)"
nb-gaussian,"(0.556, 0.571)","(0.536, 0.547)","(0.569, 0.58)","(0.547, 0.557)","(0.54, 0.551)"
svc,"(0.741, 0.757)","(0.575, 0.587)","(0.672, 0.681)","(0.635, 0.644)","(0.628, 0.638)"

****************
*** p = 10000 ***
****************

*** n = 200, N_z = 125 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.953, 0.958)","(0.495, 0.51)","(0.701, 0.713)","(0.514, 0.531)","(0.68, 0.691)"
lr,"(0.902, 0.908)","(0.497, 0.512)","(0.659, 0.672)","(0.519, 0.532)","(0.641, 0.651)"
nb-gaussian,"(0.565, 0.589)","(0.482, 0.495)","(0.514, 0.531)","(0.551, 0.566)","(0.512, 0.521)"
svc,"(0.881, 0.892)","(0.489, 0.514)","(0.725, 0.736)","(0.533, 0.548)","(0.715, 0.724)"

*** n = 200, N_z = 250 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.932, 0.935)","(0.542, 0.557)","(0.667, 0.682)","(0.534, 0.55)","(0.614, 0.634)"
lr,"(0.822, 0.832)","(0.522, 0.538)","(0.701, 0.716)","(0.525, 0.538)","(0.621, 0.636)"
nb-gaussian,"(0.522, 0.554)","(0.497, 0.513)","(0.618, 0.636)","(0.503, 0.521)","(0.566, 0.584)"
svc,"(0.845, 0.861)","(0.546, 0.566)","(0.697, 0.712)","(0.537, 0.557)","(0.645, 0.662)"

*** n = 200, N_z = 500 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.845, 0.855)","(0.527, 0.543)","(0.632, 0.649)","(0.552, 0.568)","(0.611, 0.629)"
lr,"(0.741, 0.748)","(0.51, 0.519)","(0.646, 0.66)","(0.558, 0.573)","(0.611, 0.623)"
nb-gaussian,"(0.55, 0.574)","(0.497, 0.511)","(0.582, 0.6)","(0.5, 0.517)","(0.553, 0.566)"
svc,"(0.773, 0.788)","(0.55, 0.564)","(0.662, 0.677)","(0.587, 0.605)","(0.642, 0.655)"

*** n = 200, N_z = 1000 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.918, 0.925)","(0.575, 0.593)","(0.65, 0.675)","(0.62, 0.641)","(0.619, 0.639)"
lr,"(0.637, 0.651)","(0.522, 0.537)","(0.542, 0.558)","(0.583, 0.595)","(0.545, 0.558)"
nb-gaussian,"(0.486, 0.516)","(0.484, 0.499)","(0.492, 0.514)","(0.47, 0.488)","(0.492, 0.508)"
svc,"(0.648, 0.689)","(0.563, 0.587)","(0.583, 0.605)","(0.625, 0.644)","(0.578, 0.596)"

*** n = 250, N_z = 125 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.964, 0.966)","(0.516, 0.529)","(0.802, 0.809)","(0.507, 0.519)","(0.805, 0.812)"
lr,"(0.913, 0.918)","(0.506, 0.514)","(0.759, 0.768)","(0.497, 0.508)","(0.776, 0.783)"
nb-gaussian,"(0.574, 0.592)","(0.501, 0.515)","(0.607, 0.618)","(0.51, 0.523)","(0.603, 0.612)"
svc,"(0.912, 0.918)","(0.528, 0.544)","(0.858, 0.866)","(0.537, 0.551)","(0.859, 0.866)"

*** n = 250, N_z = 250 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.955, 0.957)","(0.541, 0.554)","(0.73, 0.738)","(0.571, 0.582)","(0.696, 0.708)"
lr,"(0.876, 0.881)","(0.516, 0.528)","(0.713, 0.72)","(0.554, 0.567)","(0.674, 0.684)"
nb-gaussian,"(0.587, 0.61)","(0.521, 0.533)","(0.589, 0.598)","(0.51, 0.524)","(0.58, 0.589)"
svc,"(0.878, 0.885)","(0.566, 0.584)","(0.791, 0.798)","(0.606, 0.617)","(0.732, 0.742)"

*** n = 250, N_z = 500 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.928, 0.931)","(0.541, 0.553)","(0.649, 0.659)","(0.56, 0.571)","(0.597, 0.608)"
lr,"(0.725, 0.734)","(0.524, 0.534)","(0.583, 0.593)","(0.55, 0.559)","(0.565, 0.575)"
nb-gaussian,"(0.511, 0.531)","(0.51, 0.522)","(0.545, 0.558)","(0.516, 0.526)","(0.524, 0.536)"
svc,"(0.766, 0.782)","(0.566, 0.579)","(0.637, 0.648)","(0.595, 0.609)","(0.611, 0.621)"

*** n = 250, N_z = 1000 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.928, 0.933)","(0.581, 0.597)","(0.675, 0.689)","(0.576, 0.59)","(0.634, 0.649)"
lr,"(0.674, 0.684)","(0.552, 0.562)","(0.612, 0.621)","(0.55, 0.56)","(0.587, 0.598)"
nb-gaussian,"(0.589, 0.609)","(0.523, 0.536)","(0.581, 0.595)","(0.511, 0.525)","(0.541, 0.553)"
svc,"(0.753, 0.771)","(0.604, 0.62)","(0.654, 0.665)","(0.588, 0.601)","(0.64, 0.652)"

*** n = 333, N_z = 125 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.958, 0.96)","(0.506, 0.517)","(0.854, 0.861)","(0.497, 0.51)","(0.844, 0.849)"
lr,"(0.918, 0.922)","(0.501, 0.509)","(0.819, 0.825)","(0.499, 0.507)","(0.842, 0.847)"
nb-gaussian,"(0.58, 0.595)","(0.505, 0.512)","(0.691, 0.7)","(0.462, 0.471)","(0.686, 0.694)"
svc,"(0.926, 0.93)","(0.505, 0.52)","(0.898, 0.902)","(0.503, 0.517)","(0.898, 0.901)"

*** n = 333, N_z = 250 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.952, 0.954)","(0.524, 0.535)","(0.72, 0.73)","(0.55, 0.56)","(0.683, 0.693)"
lr,"(0.882, 0.886)","(0.493, 0.503)","(0.672, 0.68)","(0.521, 0.53)","(0.649, 0.657)"
nb-gaussian,"(0.535, 0.549)","(0.509, 0.521)","(0.588, 0.599)","(0.514, 0.524)","(0.564, 0.572)"
svc,"(0.904, 0.91)","(0.533, 0.546)","(0.764, 0.773)","(0.586, 0.596)","(0.724, 0.733)"

*** n = 333, N_z = 500 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.933, 0.936)","(0.551, 0.561)","(0.668, 0.688)","(0.55, 0.558)","(0.624, 0.635)"
lr,"(0.751, 0.757)","(0.524, 0.533)","(0.629, 0.638)","(0.501, 0.509)","(0.604, 0.612)"
nb-gaussian,"(0.587, 0.602)","(0.507, 0.518)","(0.541, 0.553)","(0.489, 0.499)","(0.505, 0.514)"
svc,"(0.813, 0.822)","(0.586, 0.599)","(0.712, 0.721)","(0.569, 0.579)","(0.665, 0.673)"

*** n = 333, N_z = 1000 ***

,full,random,k-best,k-best-mi,pk-lpnn
knn,"(0.937, 0.939)","(0.579, 0.591)","(0.658, 0.667)","(0.62, 0.631)","(0.649, 0.656)"
lr,"(0.705, 0.712)","(0.557, 0.564)","(0.589, 0.596)","(0.588, 0.596)","(0.598, 0.604)"
nb-gaussian,"(0.615, 0.629)","(0.53, 0.54)","(0.534, 0.544)","(0.544, 0.553)","(0.541, 0.548)"
svc,"(0.76, 0.773)","(0.601, 0.612)","(0.624, 0.634)","(0.641, 0.652)","(0.645, 0.652)"

**Remarks**

- For sparse-pca, the computation time increases with the number of selected features.
- For Pk-LPNN, this is not the case: computation time independent from nb of selected features.
- Pk-LPNN seems more robust: constant solid results across datasets, as opposed to sparse-pca (good and bad).
- Pk-LPNN beats k-best in some cases.
- **For the Prostate dataset, Pk-LPNN is the best method!**
- For other datasets, no clear pattern.
- Our approach open the research avenue for using compressive sampling methods for feature selection.

**Questions**
- Diminuer alpha pour sparse-pca ?
- Ajouter un dataset synthÃ©tique ?
- Ajouter un dataset multiclasse binarisÃ© ?
- Ajouter $N_z$ Ã  15% ?